In [4]:
import numpy as np
import pandas as pd

list1 = [1,2,3,4]
array1 = np.array(list1)
print(array1)

list2 = [[1,2,3],[4,5,6]]
array2 = np.array(list2)
print(array2)

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])
               
# Adding 1 to every element
print ("Adding 1 to every element:", a + 1)
 
# Subtracting 2 from each element
print ("\nSubtracting 2 from each element:", b - 2)
 
# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())
 
# Adding two arrays
# Performing Binary operations
print ("\nArray sum:\n", a + b)

list1 = [1, 2, 3, 4, 5, 6]
list2 = [10, 9, 8, 7, 6, 5]
 
# Convert list1 into a NumPy array
a1 = np.array(list1)
 
# Convert list2 into a NumPy array
a2 = np.array(list2)
 
print(a1*a2)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]
Adding 1 to every element: [[2 3]
 [4 5]]

Subtracting 2 from each element: [[ 2  1]
 [ 0 -1]]

Sum of all array elements:  10

Array sum:
 [[5 5]
 [5 5]]

In [5]:
toyPrices = np.array([5,8,3,6])
print(toyPrices - 2)

toyPrices = [5,8,3,6]
# print(toyPrices - 2) -- Not possible. Causes an error
for i in range(len(toyPrices)):
    toyPrices[i] -= 2
print(toyPrices)

arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]]) 
# Slicing array
temp = arr[:2, ::2]
print ("Array with first 2 rows and alternate"
                    "columns(0 and 2):\n", temp)
  
# Integer array indexing example
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1),"
                                    "(3, 0):\n", temp)
  
# boolean array indexing example
cond = arr > 0 # cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)

[3 6 1 4]
[3, 6, 1, 4]
Array with first 2 rows and alternatecolumns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1),(3, 0):
 [4. 6. 0. 3.]

Elements greater than 0:
 [2.  4.  4.  6.  2.6 7.  8.  3.  4.  2. ]

In [13]:
ages = np.array([13,25,19])
series1 = pd.Series(ages)
print(series1)

ages = np.array([13,25,19])
series1 = pd.Series(ages,index=['Emma', 'Swetha', 'Serajh'])
print(series1)

ages = np.array([13,25,19])
print(ages)

dates = pd.date_range("20130101", periods=6)
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
print(df)
dataf = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
    ],
    columns=['name','address','age'])

dataf.set_index('name')

df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)
print(df2.dtypes)

print(df.head())
print(df.tail(3))
print("\n")
print(df.index)
print(df.columns)
print("\n")
print(df.sort_index(axis=1, ascending=False))

0    13
1    25
2    19
dtype: int32
Emma      13
Swetha    25
Serajh    19
dtype: int32
[13 25 19]
                   A         B         C         D
2013-01-01 -1.334593  0.473603 -1.790621  2.082470
2013-01-02 -1.395623  1.401316 -0.190978  0.167563
2013-01-03 -1.330949 -0.070327 -0.172502  1.559996
2013-01-04 -0.272512  0.857098 -0.991233  0.445424
2013-01-05 -0.466795  0.960137 -1.018488  0.011067
2013-01-06  1.643553 -0.309496  0.004586 -0.310672
     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object
                   A         B         C         D
2013-01-01 -1.334593  0.473603 -1.790621  2.082470
2013-01-02 -1.395623  1.401316 -0.190978  0.167563
2013-01-03 -1.330949 -0.070327 -0.172502  1.559996
2013-01-04 -0.272512  0.857098 -0.991233  0.445424
2013-01-05 -0.466795  0.960137 -1.018488  0.011067
                   A         B         C         D
2013-01-04 -0.272512  0.857098 -0.991233  0.445424
2013-01-05 -0.466795  0.960137 -1.018488  0.011067
2013-01-06  1.643553 -0.309496  0.004586 -0.310672


DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['A', 'B', 'C', 'D'], dtype='object')


                   D         C         B         A
2013-01-01  2.082470 -1.790621  0.473603 -1.334593
2013-01-02  0.167563 -0.190978  1.401316 -1.395623
2013-01-03  1.559996 -0.172502 -0.070327 -1.330949
2013-01-04  0.445424 -0.991233  0.857098 -0.272512
2013-01-05  0.011067 -1.018488  0.960137 -0.466795
2013-01-06 -0.310672  0.004586 -0.309496  1.643553